import { FileImage, FileOutput, Minimize2, FileText, Image, Stamp, FileType, Link, Scroll, Languages, Scaling, Crop, Film, RotateCw, Grid3x3, Info, Rows, Clock, Music, Scissors, FileAudio, Coins, QrCode, Braces, Files, GitCompare, Calculator, Binary, ScanLine, KeyRound, Scale, Ruler, Thermometer, Gauge, Monitor, Activity, Users, Cat, Dog } from 'lucide-react';
import { ToolCategory, ToolDefinition } from './types';

export const APP_NAME = "枫叶工具箱";

export const TOOLS: ToolDefinition[] = [
  {
    id: 'pdf-to-png',
    name: 'PDF 转 PNG',
    description: '将 PDF 页面转换为高质量 PNG 图片。',
    path: '/pdf-to-png',
    icon: FileOutput,
    category: ToolCategory.PDF,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF 转 Word',
    description: '提取 PDF 中的文本并转换为 Word 文档 (Docx)。',
    path: '/pdf-to-word',
    icon: FileText,
    category: ToolCategory.PDF,
  },
  {
    id: 'word-to-pdf',
    name: 'Word 转 PDF',
    description: '将 Word 文档转换为 PDF 格式。',
    path: '/word-to-pdf',
    icon: FileType,
    category: ToolCategory.PDF,
  },
  {
    id: 'pdf-merger',
    name: 'PDF 合并',
    description: '将多个 PDF 文件合并为一个文件，支持调整顺序。',
    path: '/pdf-merger',
    icon: Files,
    category: ToolCategory.PDF,
  },
  {
    id: 'png-to-jpg',
    name: 'PNG 转 JPG',
    description: '将透明 PNG 转换为 JPG 格式，自定义背景颜色处理。',
    path: '/png-to-jpg',
    icon: FileImage,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-to-pdf',
    name: '图片 转 PDF',
    description: '将多张图片合并为一个 PDF 文件。',
    path: '/image-to-pdf',
    icon: Image,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-joiner',
    name: '图片拼接',
    description: '将多张图片拼接成长图，支持横向和纵向拼接，自由调整顺序。',
    path: '/image-joiner',
    icon: Rows,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'exif-viewer',
    name: '图片信息 (EXIF)',
    description: '查看图片拍摄参数、设备信息、拍摄时间等 EXIF 元数据。',
    path: '/exif-viewer',
    icon: Info,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-resizer',
    name: '修改分辨率',
    description: '调整图片的像素尺寸，支持锁定长宽比。',
    path: '/image-resizer',
    icon: Scaling,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-rotator',
    name: '图片旋转/翻转',
    description: '调整图片方向，支持45度旋转和水平/垂直翻转。',
    path: '/image-rotator',
    icon: RotateCw,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-cropper',
    name: '图片裁剪',
    description: '自由裁剪图片或使用固定比例裁剪。',
    path: '/image-cropper',
    icon: Crop,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-splitter',
    name: '图片切片',
    description: '将图片切割为 3x3 (九宫格) 或自定义网格，支持一键打包下载。',
    path: '/image-splitter',
    icon: Grid3x3,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'watermark',
    name: '图片水印',
    description: '为图片添加文字水印，支持不同强度和样式。',
    path: '/watermark',
    icon: Stamp,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'compressor',
    name: '图片压缩',
    description: '在保持视觉质量的同时减小图片文件大小。',
    path: '/compressor',
    icon: Minimize2,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-to-ico',
    name: '图片转 ICO',
    description: '将 PNG/JPG 图片转换为标准的 Windows 图标文件 (.ico)，包含多种尺寸。',
    path: '/image-to-ico',
    icon: Monitor,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'video-to-images',
    name: '视频 提取图片',
    description: '按指定帧率将视频转换为图片序列，一键导出。',
    path: '/video-to-images',
    icon: Film,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-to-audio',
    name: '提取视频音频',
    description: '从视频文件中提取 MP3 音频流。',
    path: '/video-to-audio',
    icon: FileAudio,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-trimmer',
    name: '视频裁切',
    description: '截取视频的指定片段。',
    path: '/video-trimmer',
    icon: Scissors,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-compressor',
    name: '视频压缩',
    description: '压缩视频文件大小，支持调整压缩质量。',
    path: '/video-compressor',
    icon: Minimize2,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'audio-trimmer',
    name: '音频裁切',
    description: '截取音频文件的指定片段。',
    path: '/audio-trimmer',
    icon: Music,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'url-tool',
    name: 'URL 编解码',
    description: '对 URL 进行编码或解码，处理特殊字符。',
    path: '/url-tool',
    icon: Link,
    category: ToolCategory.TEXT,
  },
  {
    id: 'baijiaxing',
    name: '百家姓加密',
    description: '将文本加密为百家姓序列，或者解密还原。',
    path: '/baijiaxing',
    icon: Languages,
    category: ToolCategory.TEXT,
  },
  {
    id: 'buddha',
    name: '佛曰加密',
    description: '经典的“佛曰”文本混淆加密与解密工具。',
    path: '/buddha',
    icon: Scroll,
    category: ToolCategory.TEXT,
  },
  {
    id: 'word-counter',
    name: '字数统计',
    description: '实时统计字符数、单词数、行数，支持中英文区分。',
    path: '/word-counter',
    icon: Calculator,
    category: ToolCategory.TEXT,
  },
  {
    id: 'base64',
    name: 'Base64 转换',
    description: '文本和图片与 Base64 编码之间的相互转换工具。',
    path: '/base64',
    icon: Binary,
    category: ToolCategory.DEV,
  },
  {
    id: 'text-diff',
    name: '文本对比',
    description: '对比两段文本或代码的差异，高亮显示不同之处。',
    path: '/text-diff',
    icon: GitCompare,
    category: ToolCategory.DEV,
  },
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: 'JSON 数据格式化、压缩、验证及高亮显示。',
    path: '/json-formatter',
    icon: Braces,
    category: ToolCategory.DEV,
  },
  {
    id: 'timestamp',
    name: '时间戳工具',
    description: 'Unix 时间戳转换、实时监控、时间加减计算。',
    path: '/timestamp',
    icon: Clock,
    category: ToolCategory.DEV,
  },
  {
    id: 'base-converter',
    name: '进制转换',
    description: '二进制、八进制、十进制、十六进制之间的实时互转。',
    path: '/base-converter',
    icon: Binary,
    category: ToolCategory.DEV,
  },
  {
    id: 'currency-converter',
    name: '汇率换算',
    description: '实时查询全球货币汇率并进行换算。',
    path: '/currency-converter',
    icon: Coins,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'qrcode-generator',
    name: '二维码生成',
    description: '将文本、网址生成二维码，支持自定义颜色和下载。',
    path: '/qrcode-generator',
    icon: QrCode,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'qrcode-decoder',
    name: '二维码解析',
    description: '上传二维码图片，自动识别并提取其中的文本或网址信息。',
    path: '/qrcode-decoder',
    icon: ScanLine,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'password-generator',
    name: '随机密码生成',
    description: '生成包含大小写、数字、符号的高强度随机密码。',
    path: '/password-generator',
    icon: KeyRound,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-weight',
    name: '重量单位换算',
    description: '千克、磅、盎司、克等重量单位的相互换算。',
    path: '/unit-weight',
    icon: Scale,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-length',
    name: '长度单位换算',
    description: '米、千米、英里、英寸、尺等长度单位的相互换算。',
    path: '/unit-length',
    icon: Ruler,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-temperature',
    name: '温度单位换算',
    description: '摄氏度、华氏度、开尔文之间的相互换算。',
    path: '/unit-temperature',
    icon: Thermometer,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-pressure',
    name: '压力单位换算',
    description: '帕斯卡、巴、标准大气压、psi 等压力单位换算。',
    path: '/unit-pressure',
    icon: Gauge,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI 计算器',
    description: '计算身体质量指数 (BMI) 并评估健康状况。',
    path: '/bmi-calculator',
    icon: Activity,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'kinship-calculator',
    name: '亲戚称呼计算器',
    description: '查询复杂的中国亲戚关系称呼，支持层级推算。',
    path: '/kinship-calculator',
    icon: Users,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'cat-age',
    name: '猫猫年龄计算',
    description: '科学换算猫咪的年龄对应的人类年龄。',
    path: '/cat-age',
    icon: Cat,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'dog-age',
    name: '狗狗年龄计算',
    description: '根据体型科学换算狗狗的年龄对应的人类年龄。',
    path: '/dog-age',
    icon: Dog,
    category: ToolCategory.UTILITY,
  }
];