import { FileImage, FileOutput, Minimize2, FileText, Image, Stamp, FileType, Link, Scroll, Languages, Scaling, Crop, Film, RotateCw, Grid3x3, Info, Rows, Clock, Music, Scissors, FileAudio, Coins, QrCode, Braces, Files, GitCompare, Calculator, Binary, ScanLine, KeyRound, Scale, Ruler, Thermometer, Gauge, Monitor, Activity, Users, Cat, Dog, Sparkles, RefreshCw, Volume2, Waves, Fingerprint, Tag, Palette, FileCheck, FileCode, Grid, LayoutGrid, Square, Type, Regex, Table2 } from 'lucide-react';
import { ToolCategory, ToolDefinition } from './types';

export const APP_NAME = "枫叶工具箱";

export const TOOLS: ToolDefinition[] = [
  {
    id: 'pdf-to-png',
    name: 'PDF 转 PNG',
    description: '将 PDF 页面转换为高质量 PNG 图片。',
    path: '/pdf-to-png',
    icon: FileOutput,
    category: ToolCategory.PDF,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF 转 Word',
    description: '提取 PDF 中的文本并转换为 Word 文档 (Docx)。',
    path: '/pdf-to-word',
    icon: FileText,
    category: ToolCategory.PDF,
  },
  {
    id: 'word-to-pdf',
    name: 'Word 转 PDF',
    description: '将 Word 文档转换为 PDF 格式。',
    path: '/word-to-pdf',
    icon: FileType,
    category: ToolCategory.PDF,
  },
  {
    id: 'pdf-merger',
    name: 'PDF 合并',
    description: '将多个 PDF 文件合并为一个文件，支持调整顺序。',
    path: '/pdf-merger',
    icon: Files,
    category: ToolCategory.PDF,
  },
  {
    id: 'png-to-jpg',
    name: 'PNG 转 JPG',
    description: '将透明 PNG 转换为 JPG 格式，自定义背景颜色处理。',
    path: '/png-to-jpg',
    icon: FileImage,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-to-pdf',
    name: '图片 转 PDF',
    description: '将多张图片合并为一个 PDF 文件。',
    path: '/image-to-pdf',
    icon: Image,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-joiner',
    name: '图片拼接',
    description: '将多张图片拼接成长图，支持横向和纵向拼接，自由调整顺序。',
    path: '/image-joiner',
    icon: Rows,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'exif-viewer',
    name: '图片信息 (EXIF)',
    description: '查看图片拍摄参数、设备信息、拍摄时间等 EXIF 元数据。',
    path: '/exif-viewer',
    icon: Info,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-resizer',
    name: '修改分辨率',
    description: '调整图片的像素尺寸，支持锁定长宽比。',
    path: '/image-resizer',
    icon: Scaling,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-rotator',
    name: '图片旋转/翻转',
    description: '调整图片方向，支持45度旋转和水平/垂直翻转。',
    path: '/image-rotator',
    icon: RotateCw,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-cropper',
    name: '图片裁剪',
    description: '自由裁剪图片或使用固定比例裁剪。',
    path: '/image-cropper',
    icon: Crop,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-splitter',
    name: '图片切片',
    description: '将图片切割为 3x3 (九宫格) 或自定义网格，支持一键打包下载。',
    path: '/image-splitter',
    icon: Grid3x3,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'watermark',
    name: '图片水印',
    description: '为图片添加文字水印，支持不同强度和样式。',
    path: '/watermark',
    icon: Stamp,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'compressor',
    name: '图片压缩',
    description: '在保持视觉质量的同时减小图片文件大小。',
    path: '/compressor',
    icon: Minimize2,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-to-ico',
    name: '图片转 ICO',
    description: '将 PNG/JPG 图片转换为标准的 Windows 图标文件 (.ico)，包含多种尺寸。',
    path: '/image-to-ico',
    icon: Monitor,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'sprite-sheet-splitter',
    name: '精灵表切割器',
    description: '上传 Sprite Sheet 大图，按每帧宽高或行列数切割成单张图片，支持打包 ZIP 下载。',
    path: '/sprite-sheet-splitter',
    icon: Grid,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'sprite-sheet-generator',
    name: '精灵表生成器',
    description: '上传多张序列帧图片，按行列排列合并成一张 Sprite Sheet，可下载。',
    path: '/sprite-sheet-generator',
    icon: LayoutGrid,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'texture-power-of-two',
    name: '纹理 2 的幂次调整',
    description: '将图片尺寸调整为最近的 2^n（如 512×512），支持多种缩放模式。',
    path: '/texture-power-of-two',
    icon: Square,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'batch-image-rename',
    name: '批量图片重命名',
    description: '上传多张图片，设置命名规则（如 prefix_001、frame_{index}），预览后打包下载。',
    path: '/batch-image-rename',
    icon: FileText,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'color-palette-extractor',
    name: '颜色板生成',
    description: '上传图片，提取主色调（K-means 或简单采样），生成配色方案，显示 Hex/RGB。',
    path: '/color-palette-extractor',
    icon: Palette,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'ascii-art-generator',
    name: 'ASCII 艺术生成',
    description: '上传图片，转换为 ASCII 字符图，可调节字符密度和宽度。',
    path: '/ascii-art-generator',
    icon: Type,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'svg-to-png',
    name: 'SVG 转 PNG',
    description: '上传 SVG 文件，设置输出尺寸，转换为 PNG 下载。',
    path: '/svg-to-png',
    icon: FileImage,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'gif-splitter',
    name: 'GIF 分解',
    description: '上传 GIF，分解为帧序列图片，打包 ZIP 下载。',
    path: '/gif-splitter',
    icon: Film,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'gif-composer',
    name: 'GIF 合成',
    description: '上传多张图片，设置帧间隔，合成 GIF 动图。',
    path: '/gif-composer',
    icon: Film,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'image-background-remover',
    name: '图片抠背景',
    description: 'AI 智能移除图片背景，完全本地处理，保护隐私。',
    path: '/image-background-remover',
    icon: Scissors,
    category: ToolCategory.IMAGE,
  },
  {
    id: 'video-to-images',
    name: '视频 提取图片',
    description: '按指定帧率将视频转换为图片序列，一键导出。',
    path: '/video-to-images',
    icon: Film,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'image-sequence-player',
    name: '序列图播放',
    description: '预览图片序列是否连贯，支持多选或选择文件夹。',
    path: '/image-sequence-player',
    icon: Film,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-to-audio',
    name: '提取视频音频',
    description: '从视频文件中提取 MP3 音频流。',
    path: '/video-to-audio',
    icon: FileAudio,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-trimmer',
    name: '视频裁切',
    description: '截取视频的指定片段。',
    path: '/video-trimmer',
    icon: Scissors,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'video-compressor',
    name: '视频压缩',
    description: '压缩视频文件大小，支持调整压缩质量。',
    path: '/video-compressor',
    icon: Minimize2,
    category: ToolCategory.VIDEO,
  },
  {
    id: 'audio-trimmer',
    name: '音频裁切',
    description: '截取音频文件的指定片段。',
    path: '/audio-trimmer',
    icon: Music,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'audio-format-converter',
    name: '音频格式转换',
    description: 'WAV、MP3、OGG、AAC、FLAC 等格式互转。',
    path: '/audio-format-converter',
    icon: RefreshCw,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'audio-normalizer',
    name: '音频归一化',
    description: '统一音量到目标响度，支持 loudnorm 或 volume 模式。',
    path: '/audio-normalizer',
    icon: Volume2,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'audio-fade-in-out',
    name: '音频淡入淡出',
    description: '为音频添加淡入、淡出效果，平滑开始与结束。',
    path: '/audio-fade-in-out',
    icon: Waves,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'bpm-detector',
    name: 'BPM 检测',
    description: '基于 Web Audio API 的节奏估算，适合有明显节拍的音频。',
    path: '/bpm-detector',
    icon: Activity,
    category: ToolCategory.AUDIO,
  },
  {
    id: 'url-tool',
    name: 'URL 编解码',
    description: '对 URL 进行编码或解码，处理特殊字符。',
    path: '/url-tool',
    icon: Link,
    category: ToolCategory.TEXT,
  },
  {
    id: 'baijiaxing',
    name: '百家姓加密',
    description: '将文本加密为百家姓序列，或者解密还原。',
    path: '/baijiaxing',
    icon: Languages,
    category: ToolCategory.TEXT,
  },
  {
    id: 'buddha',
    name: '佛曰加密',
    description: '经典的“佛曰”文本混淆加密与解密工具。',
    path: '/buddha',
    icon: Scroll,
    category: ToolCategory.TEXT,
  },
  {
    id: 'word-counter',
    name: '字数统计',
    description: '实时统计字符数、单词数、行数，支持中英文区分。',
    path: '/word-counter',
    icon: Calculator,
    category: ToolCategory.TEXT,
  },
  {
    id: 'base64',
    name: 'Base64 转换',
    description: '文本和图片与 Base64 编码之间的相互转换工具。',
    path: '/base64',
    icon: Binary,
    category: ToolCategory.DEV,
  },
  {
    id: 'text-diff',
    name: '文本对比',
    description: '对比两段文本或代码的差异，高亮显示不同之处。',
    path: '/text-diff',
    icon: GitCompare,
    category: ToolCategory.DEV,
  },
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: 'JSON 数据格式化、压缩、验证及高亮显示。',
    path: '/json-formatter',
    icon: Braces,
    category: ToolCategory.DEV,
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema 校验',
    description: '使用 JSON Schema 校验 JSON 数据是否符合规范。',
    path: '/json-schema-validator',
    icon: FileCheck,
    category: ToolCategory.DEV,
  },
  {
    id: 'lua-formatter',
    name: 'Lua 格式化',
    description: '格式化 Lua 代码，2 空格缩进，简单括号匹配检查。',
    path: '/lua-formatter',
    icon: FileCode,
    category: ToolCategory.DEV,
  },
  {
    id: 'xml-formatter',
    name: 'XML 格式化',
    description: '格式化 XML 文档，2 空格缩进，基本格式验证。',
    path: '/xml-formatter',
    icon: FileCode,
    category: ToolCategory.DEV,
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    description: '测试正则表达式，实时高亮匹配结果，显示捕获组。',
    path: '/regex-tester',
    icon: Regex,
    category: ToolCategory.DEV,
  },
  {
    id: 'csv-to-json',
    name: 'CSV 转 JSON',
    description: '将 CSV 解析为 JSON 数组，支持自定义分隔符，可下载。',
    path: '/csv-to-json',
    icon: FileText,
    category: ToolCategory.DEV,
  },
  {
    id: 'localization-extractor',
    name: '本地化字符串提取',
    description: '从代码中提取 i18n、t()、L[] 等模式的 key，导出 JSON/CSV。',
    path: '/localization-extractor',
    icon: Languages,
    category: ToolCategory.DEV,
  },
  {
    id: 'localization-table',
    name: '多语言对照表',
    description: '管理 key-value 翻译表，支持多语言列，导入/导出 CSV、JSON。',
    path: '/localization-table',
    icon: Table2,
    category: ToolCategory.DEV,
  },
  {
    id: 'translation-missing-checker',
    name: '翻译缺失检测',
    description: '对比多语言 JSON 文件，检测各语言缺失的 key。',
    path: '/translation-missing-checker',
    icon: Languages,
    category: ToolCategory.DEV,
  },
  {
    id: 'timestamp',
    name: '时间戳工具',
    description: 'Unix 时间戳转换、实时监控、时间加减计算。',
    path: '/timestamp',
    icon: Clock,
    category: ToolCategory.DEV,
  },
  {
    id: 'base-converter',
    name: '进制转换',
    description: '二进制、八进制、十进制、十六进制之间的实时互转。',
    path: '/base-converter',
    icon: Binary,
    category: ToolCategory.DEV,
  },
  {
    id: 'uuid-generator',
    name: 'UUID 生成',
    description: '一键生成 UUID v4，支持批量生成与复制。',
    path: '/uuid-generator',
    icon: Fingerprint,
    category: ToolCategory.DEV,
  },
  {
    id: 'version-generator',
    name: '版本号生成器',
    description: '输入 major.minor.patch，生成语义化版本号，支持 beta/alpha 后缀。',
    path: '/version-generator',
    icon: Tag,
    category: ToolCategory.DEV,
  },
  {
    id: 'color-converter',
    name: '颜色格式转换',
    description: 'Hex、RGB、HSL、Unity Color 之间互转，实时预览色块。',
    path: '/color-converter',
    icon: Palette,
    category: ToolCategory.DEV,
  },
  {
    id: 'file-hash-checker',
    name: '文件哈希校验',
    description: '上传文件计算 MD5/SHA-256，支持粘贴哈希值比对。',
    path: '/file-hash-checker',
    icon: FileCheck,
    category: ToolCategory.DEV,
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown 转 HTML',
    description: '输入 Markdown 实时渲染为 HTML，可复制或下载。',
    path: '/markdown-to-html',
    icon: FileCode,
    category: ToolCategory.DEV,
  },
  {
    id: 'ue-blueprint-slimmer',
    name: 'UE 蓝图 Token 瘦身',
    description: '提炼 UE 蓝图复制文本中的节点关系与关键信息，生成更精简的逻辑摘要。',
    path: '/ue-blueprint-slimmer',
    icon: Minimize2,
    category: ToolCategory.DEV,
  },
  {
    id: 'prompt-optimizer',
    name: 'DeepSeek 提示词优化',
    description: '将口语化、表达模糊的提问转化为专业、术语准确、逻辑清晰的 Prompt。',
    path: '/prompt-optimizer',
    icon: Sparkles,
    category: ToolCategory.DEV,
  },
  {
    id: 'currency-converter',
    name: '汇率换算',
    description: '实时查询全球货币汇率并进行换算。',
    path: '/currency-converter',
    icon: Coins,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'qrcode-generator',
    name: '二维码生成',
    description: '将文本、网址生成二维码，支持自定义颜色和下载。',
    path: '/qrcode-generator',
    icon: QrCode,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'qrcode-decoder',
    name: '二维码解析',
    description: '上传二维码图片，自动识别并提取其中的文本或网址信息。',
    path: '/qrcode-decoder',
    icon: ScanLine,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'password-generator',
    name: '随机密码生成',
    description: '生成包含大小写、数字、符号的高强度随机密码。',
    path: '/password-generator',
    icon: KeyRound,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-weight',
    name: '重量单位换算',
    description: '千克、磅、盎司、克等重量单位的相互换算。',
    path: '/unit-weight',
    icon: Scale,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-length',
    name: '长度单位换算',
    description: '米、千米、英里、英寸、尺等长度单位的相互换算。',
    path: '/unit-length',
    icon: Ruler,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-temperature',
    name: '温度单位换算',
    description: '摄氏度、华氏度、开尔文之间的相互换算。',
    path: '/unit-temperature',
    icon: Thermometer,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'unit-pressure',
    name: '压力单位换算',
    description: '帕斯卡、巴、标准大气压、psi 等压力单位换算。',
    path: '/unit-pressure',
    icon: Gauge,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI 计算器',
    description: '计算身体质量指数 (BMI) 并评估健康状况。',
    path: '/bmi-calculator',
    icon: Activity,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'kinship-calculator',
    name: '亲戚称呼计算器',
    description: '查询复杂的中国亲戚关系称呼，支持层级推算。',
    path: '/kinship-calculator',
    icon: Users,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'cat-age',
    name: '猫猫年龄计算',
    description: '科学换算猫咪的年龄对应的人类年龄。',
    path: '/cat-age',
    icon: Cat,
    category: ToolCategory.UTILITY,
  },
  {
    id: 'dog-age',
    name: '狗狗年龄计算',
    description: '根据体型科学换算狗狗的年龄对应的人类年龄。',
    path: '/dog-age',
    icon: Dog,
    category: ToolCategory.UTILITY,
  }
];